[project]
name = "finetunning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.5.0",
    "evaluate>=0.4.6",
    "huggingface-hub>=1.4.1",
    "ipywidgets>=8.1.8",
    "peft",        # For LoRA and QLoRA
    "bitsandbytes",# For 4-bit quantization
    "tiktoken",    # Tokenizer for GPT-2
    "python-dotenv>=1.2.1",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0",
    "transformers>=5.2.0",
    "pydantic-settings>=2.13.1",
    "pytest>=9.0.2",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cpu" }]
torchvision = [{ index = "pytorch-cpu" }]
torchaudio = [{ index = "pytorch-cpu" }]
